spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: development
    url: jdbc:postgresql://localhost:5432/loja
    
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
